version: '3.8'

services:
  frontend:
    image: angular-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/news-app/browser:/usr/share/nginx/html:ro
